### ISSUE TITLE
Get code ready for communicating with the web server

### ISSUE THREAD

**Issue by AhsenBaig** [FNLHub/NodeMCU-FanProject#1]
This is so we can get the IoT device to get instructions from the web server. See https://github.com/FNLHub/IoT-Server/issues/1

**Comment by AhsenBaig** [comment]
If the issue is marked as Done we should also close out the ticket with any additional information.

**Comment by knnth3** [comment]
NodeMCU successfully connects to a remote server using Heroku and AWS
