### ISSUE TITLE
Speak to the Server thru the NodeMCU

### ISSUE THREAD

**Issue by Leopardi628** [FNLHub/NodeMCU-FanProject#4]
Data is being sent, but the signature (or confirmation) is not being received/confirmed by the NodeMCU.

**Comment by AhsenBaig** [comment]
If the issue is marked as Done we should also close out the ticket with any additional information.

**Comment by knnth3** [comment]
The connection on the nodeMCU now properly asks for the Auth header key. This allows for the software compare it and determine if connection comes from our server.
